resolver [fd12::10] valid=10s ipv6=on;

upstream backend_upstream {
    zone backend_upstream 64k;
    server doctask-rahul-ranjan.railway.internal:8000 resolve;
}

server {
    listen 80;
    server_name _;

    location /api/ {
        proxy_pass http://backend_upstream/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}